### PR TITLE
Merged Remainder and Divide 

### PR DESCRIPTION
**Pull request by MachineLearning1090**

### CODE REVIEW

**Comment by MachineLearning1090** [comment]
Heres a first pass.

**Comment by PZ1Sharer05** [comment]
> Heres a first pass.
no, don't use booleans

**Comment by MachineLearning1090** [comment]
> > Heres a first pass.
> > no, don't use booleans

What? Why? If I don't use booleans, the users are not going to level their skills

**Comment by PZ1Sharer05** [comment]
> > > Heres a first pass.
> > > no, don't use booleans
> 
> What? Why? If I don't use booleans, the users are not going to level their skills

Sorry, you are trying to against me? This is not what it meant to be, @MachineLearning1090 .
Sorry, I am shutting you down. Anyways all your work is mine now... 
I will work on all the things you failed on, @MachineLearning1090 
You will never dare to attempt to replicate my work. My work is not under the MIT License as licensed by me.

**Pull request merged**
